// MADE by AMIN
const main = document.querySelector('button#main')
const menu= document.querySelector('div#HR')
const mic = document.querySelector('button#Mico')
const vob = document.querySelector('button#vob')
const videol = document.querySelector('video#ocT')
const bplay = document.querySelector('button#playb')
const bpause = document.querySelector('button#pauseb')
const bFullS = document.querySelector('button#FullS')
const volumei = document.querySelector('input#VO')
const share = document.querySelector('button#share')
 const videolS = document.querySelector('video#octS')
 const bFullSs = document.querySelector('button#FullSs')
 const bpauses = document.querySelector('button#pausebs')
 const bplays = document.querySelector('button#playbs')
 const para = document.querySelector('div#shm')
 const btsend = document.querySelector('button#send')
 const mbi = document.querySelector('input#mbi')
//  const volume1s = document.querySelector('input#VOs')
main.addEventListener('mouseenter',()=>{menu.style.visibility='visible'})
menu.addEventListener('mouseenter',()=>{menu.style.visibility='visible'})
main.addEventListener('mouseout',()=>{menu.style.visibility='hidden'})
menu.addEventListener('mouseout',()=>{menu.style.visibility='hidden'})
function camM()
{
  mic.addEventListener('click',()=>{navigator.mediaDevices.getUserMedia({audio:true,video:true}).then((vs)=>{videol.srcObject=vs}).catch(console.log('a'))})
  // cam1.addEventListener('click',()=>{navigator.mediaDevices.getUserMedia({video:true}).then((vs)=>{videol.srcObject=vs}).catch(console.log('a'))})
  bpause.addEventListener('click',()=>{videol.pause();bpause.style.visibility="hidden" ;bplay.style.visibility="visible";})
  bplay.addEventListener('click',()=>{videol.play();bplay.style.visibility="hidden";bpause.style.visibility="visible";})
  bFullS.addEventListener('click',()=>{videol.requestFullscreen()})
  volumei.addEventListener('change',()=>{const vl = volumei.value/100 ;const vls = vl.toString() ;videol.volume = vls})
}
window.addEventListener('load',camM)
vob.addEventListener('mouseenter',()=>{volumei.style.visibility='visible'})
volumei.addEventListener('mouseenter',()=>{volumei.style.visibility='visible'})
volumei.addEventListener('mouseout',()=>{volumei.style.visibility='hidden'})
  
function Share()
{
  share.addEventListener('click',()=>{bplays.style.visibility='visible';bpauses.style.visibility='visible';bFullSs.style.visibility='visible';navigator.mediaDevices.getDisplayMedia().then((vs)=>{videolS.srcObject=vs}).catch(console.log('a'))})
  // cam1.addEventListener('click',()=>{navigator.mediaDevices.getUserMedia({video:true}).then((vs)=>{videol.srcObject=vs}).catch(console.log('a'))})
  bpauses.addEventListener('click',()=>{videolS.pause();bpauses.style.visibility="hidden" ;bplays.style.visibility="visible";})
  bplays.addEventListener('click',()=>{videolS.play();bplays.style.visibility="hidden";bpauses.style.visibility="visible";})
  bFullSs.addEventListener('click',()=>{videolS.requestFullscreen()})
  // volume1s.addEventListener('change',()=>{const vls = volume1s.value/100 ; videolS.volume = vls.toString();console.log(vl.toString());})
}
window.addEventListener('load',Share)
btsend.addEventListener('click',()=>{para.innerHTML = mbi.value;})
